version: "3.8"
services:
  database:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=remix
      - POSTGRES_PASSWORD=onetwothreefour
      - POSTGRES_DB=diskjockey
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  app:
    build: .
    image: diskjockey:latest
    depends_on:
      - database
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://remix:onetwothreefour@database:5432/diskjockey
      - SESSION_SECRET=fivesixseven
