name: CI
on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    env:
      STORE_PATH:

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.7.0

      - name: Install PNPM
        uses: pnpm/action-setup@v3

      - name: Install dependencies
        run: pnpm install

      - name: Run check
        run: pnpm run check:format

  lint:
    runs-on: ubuntu-latest
    env:
      STORE_PATH:

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.7.0

      - name: Install PNPM
        uses: pnpm/action-setup@v3

      - name: Install dependencies
        run: pnpm install

      - name: Run check
        run: pnpm run check:lint

  typecheck:
    runs-on: ubuntu-latest
    env:
      STORE_PATH:

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.7.0

      - name: Install PNPM
        uses: pnpm/action-setup@v3

      - name: Install dependencies
        run: pnpm install

      - name: Run typecheck
        run: pnpm run check:types
